### ISSUE TITLE
run main.py

### ISSUE THREAD

**Issue by ysn7** [yunjey/stargan#112]
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 40, in main
    solver = Solver(celeba_loader, rafd_loader, config)
  File "/home/yao/stargan-master/solver.py", line 70, in __init__
    self.build_tensorboard()
  File "/home/yao/stargan-master/solver.py", line 109, in build_tensorboard
    self.logger = Logger(self.log_dir)
  File "/home/yao/stargan-master/logger.py", line 9, in __init__
    self.writer = tf.summary.FileWriter(log_dir)
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

**Comment by ysn7** [comment]
how can i solve this Error?
