### ISSUE TITLE
Custom evaluation dataset

### ISSUE THREAD

**Issue by ser0t0nin** [yunjey/StarGAN#14]
Hello, thank you for your code.
I performed the training stage and got the model - works perfectly on the default datasets. Is it possible to cast the model on my custom imageset? I created a proper folder structure, created valid metafile, filled all the paths (as i think) and got error 
`The number of parameters: 44762048
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main(config)
  File "main.py", line 46, in main
    solver.test()
  File "/home/username/Documents/StarGAN/solver.py", line 679, in test
    target_c_list = self.make_celeb_labels(org_c)
  File "/home/username/Documents/StarGAN/solver.py", line 181, in make_celeb_labels
    c[i] = 0 if c[i] == 1 else 1   # opposite value
IndexError: index 4 is out of range for dimension 0 (of size 4)`
Is it possible in general? Can you provide a kind of instruction, so people can use it without tough reverse engineering? Thanks

**Comment by warisha** [comment]
You have tested this model successfully. Can you please help me?
I want to generate different expressions from neutral image... 

Test time it generate only image multiple times
1-images

**Comment by iamzhangyunlu** [comment]
> You have tested this model successfully. Can you please help me?
> I want to generate different expressions from neutral image...
> 
> Test time it generate only one image multiple times
> ![1](https://user-images.githubusercontent.com/18666252/40292595-a51a4826-5ce5-11e8-9ad4-988d50d8f505.jpg)

Have you solve the problem yet? Have you find the reason of the same expression?
