### ISSUE TITLE
Can't make project run without cuda

### ISSUE THREAD

**Issue by am-khan** [yunjey/StarGAN#15]
Hi, 

I'm trying to run the model purely on my CPU (i only have an OpenCL supported GPU).

I install pytorch wihout cuda enabled and set 

    cudnn.benchmark = False

in line13 of main.py yet still get the error:

Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main(config)
  File "main.py", line 41, in main
    solver.train()
  File "/Users/akbirkhan/Documents/CompVision/Assignment3/StarGAN/solver.py", line 299, in train
    alpha = torch.rand(real_x.size(0), 1, 1, 1).cuda().expand_as(real_x)
  File "/usr/local/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 358, in _lazy_new
    _lazy_init()
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 120, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 55, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by lianhuifang** [comment]
I met the same questions. What should I do to this problem? Please!

**Comment by yunjey** [comment]
Sorry for late reply. We fixed this issue now.
