### ISSUE TITLE
thanks for yours ! There is a error for pytorch 0.4?

### ISSUE THREAD

**Issue by zhuyanshuo** [yunjey/StarGAN#41]
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 49, in main
    solver.test()
  File "D:\pytorchdemo\StarGAN-master\solver.py", line 526, in test
    self.restore_model(self.test_iters)
  File "D:\pytorchdemo\StarGAN-master\solver.py", line 103, in restore_model
    self.G.load_state_dict(torch.load(G_path, map_location=lambda storage, loc: storage))
  File "C:\Program Files\Python35\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:

**Comment by yunjey** [comment]
@zhuyanshuo Thank you for your report. The error has occurred because the pretrained models are saved in PyTorch 0.3.  I fixed the error now. Please try it again.
