### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by yeoungmin-kim** [yunjey/StarGAN#43]
i try this code but i have this error

ConnectionRefusedError: [Errno 111] Connection refused

how can i do?

**Comment by yunjey** [comment]
Please attach the complete error message. 
If your GPU memory is smaller than 12GB, you should reduce `batch_size=16` to `batch_size=x` where `x` is a value smaller than 16.

**Comment by yeoungmin-kim** [comment]
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 44, in main
    solver.train()
  File "/home/rhee/StarGAN/solver.py", line 249, in train
    x_fake = self.G(x_real, c_trg)
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rhee/StarGAN/model.py", line 60, in forward
    return self.main(x)
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: $ Torch: not enough memory: you tried to allocate 1GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.c:218
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fbf00bbc5c0>>
Traceback (most recent call last):
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/rhee/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

I have this error message. I don`t understand run time error because my computer 8G RAM 
 What file name should I modify?

**Comment by yunjey** [comment]
Can you try running the training script with `--num_workers=0` and see if the error occurs again?
