### ISSUE TITLE
Error while running this code on same dataset 

### ISSUE THREAD

**Issue by Rabia-Raja** [yunjey/StarGAN#68]
I am running this code. But I am facing some errors. Can you help me?
The errors are: 
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 32, in main
    'CelebA', config.mode, config.num_workers)
  File "/home/chenky/rabia/star-gan/StarGAN-master/data_loader.py", line 84, in get_loader
    dataset = CelebA(image_dir, attr_path, selected_attrs, transform, mode)
  File "/home/chenky/rabia/star-gan/StarGAN-master/data_loader.py", line 24, in __init__
    self.preprocess()
  File "/home/chenky/rabia/star-gan/StarGAN-master/data_loader.py", line 49, in preprocess
    idx = self.attr2idx[attr_name]
KeyError: 'Black_Hair

**Comment by FighterFong** [comment]
Are you fix it?

**Comment by iamzhangyunlu** [comment]
> I am running this code. But I am facing some errors. Can you help me?
> The errors are:
> �Traceback (most recent call last):
> File "main.py", line 110, in
> main(config)
> File "main.py", line 32, in main
> 'CelebA', config.mode, config.num_workers)
> File "/home/chenky/rabia/star-gan/StarGAN-master/data_loader.py", line 84, in get_loader
> dataset = CelebA(image_dir, attr_path, selected_attrs, transform, mode)
> File "/home/chenky/rabia/star-gan/StarGAN-master/data_loader.py", line 24, in **init**
> self.preprocess()
> File "/home/chenky/rabia/star-gan/StarGAN-master/data_loader.py", line 49, in preprocess
> idx = self.attr2idx[attr_name]
> KeyError: 'Black_Hair

Same problem here! Have you fixed yet please? @Rabia-Raja
