### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by yangyuke001** [yunjey/stargan#94]
File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 49, in main
    solver.test()
  File "/home/yyk/GAN/starGAN/StarGAN/solver.py", line 555, in test
    for i, (x_real, c_org) in enumerate(data_loader):
  File "/home/yyk/anaconda3/envs/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/yyk/anaconda3/envs/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/yyk/anaconda3/envs/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yyk/anaconda3/envs/python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yyk/anaconda3/envs/python36/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 134, in __getitem__
    sample = self.transform(sample)
TypeError: 'list' object is not callable
 
anyone help is awesome!

**Comment by bucky999** [comment]
could you tell me how to slove this problum?
